### ISSUE TITLE
use_aliases is no longer a recognized option in emoji.emojize()

### ISSUE THREAD

**Issue by ofalk** [sopel-irc/sopel-github#118]
https://github.com/sopel-irc/sopel-github/blob/588db54d477a46bc6e8db277869a1a4240318412/sopel_modules/github/formatting.py#L31

Please remove the option use_aliases=True from this line. If you prefer, I can also send you a PR - it's pretty straight forward.

**Comment by dgw** [comment]
> remove the option use_aliases=True

Correct resolution is a little more complicated, since _only_ removing the option will sacrifice the emoji alias functionality.

It is probably time to add `emoji` as a proper requirement (maybe a setuptools extra), since this is a major API change that would be very tedious (but not impossible) to detect and adapt to at runtime.

A PR is welcome, or I will get to this myself within a week or so.

**Comment by ofalk** [comment]
Very good point. Maybe I can draft something that you can build up upon.

**Comment by ofalk** [comment]
Looking at the code, the changes and how it's supposed to be used now, it seems the change is straight forward.
