### ISSUE TITLE
Responses to links should include time information

### ISSUE THREAD

**Issue by SnoopJ** [sopel-irc/sopel-github#121]
```
<+dgw> 💭(github plugin's comment output should include the date...)
<+dgw> or relative timestamp
```

+1, links to comments (and issues!) would benefit from some additional information about when the linked-to thing occurred

**Comment by dgw** [comment]
For issues/PRs, there's the added layer of deciding _which_ timestamp to use (e.g. for open ones, when it was opened; for closed ones, when it was closed/merged).

**Comment by SnoopJ** [comment]
I'd say for those, knowing the time-of-origin is most relevant to a user on IRC, but it might also be helpful to include a last-updated time if possible?

**Comment by dgw** [comment]
Fortunately, it seems that `created_at` and `updated_at` are bog-standard data fields present on just about any entity we care about fetching from the GitHub API. That applies to issues, PRs, and comments—which is just fine, then.

Hard part will be constructing the revised message format including time(s) so that it flows nicely.
